### ISSUE TITLE
Incremental build issue

### ISSUE THREAD

**Issue by TheAngryByrd** [enricosada/dotnet-proj-info#13] opened 2017-11-21 17:56 UTC
After running `dotnet proj-info` on a project, incremental builds seem affected.

```
Input file "/dev/MyApp.fsproj.proj-info.targets" is newer than output file "/dev/Debug/net462/MyApp.exe".
```

If you need a repro let me know.

**Comment by enricosada** [comment] 2018-01-10 10:52
yes. issue is i use same file name for both `dotnet proj-info` and consumer of this library (fable/ ionide)

i'll fix that with https://github.com/enricosada/dotnet-proj-info/issues/10 removing the need for that file

**Comment by vbfox** [comment] 2018-03-29 12:45
We are affected by the same problem, made worse by the fact that proj-info seem to be called in a loop somewhere in FSAC as even when I do nothing the files a re always changed (The write time is always NOW & killing FSAC stops that).

I'll send a PR to not write the file if it's the same as otherwise except for telling our team to stop using vscode for anything F# I don't see any good solution.

**Comment by vbfox** [comment] 2018-03-29 19:48
The root cause of this issue triggering constantly for me was https://github.com/ionide/ionide-vscode-fsharp/pull/765 (So in ionide not FSAC itself)

**Comment by vbfox** [comment] 2018-04-03 07:32
Solved the last instances of ionide side in https://github.com/ionide/ionide-vscode-fsharp/pull/767 Would still love to see #17 merged ;)

**Closed** 2018-10-01 18:55 UTC
Labels: bug
